#!/system/bin/sh

### INSMOD ZRAM-MODULE ON BOOT
insmod /system/lib/modules/zram.ko;
sleep 2

### CREATE ZRAM SWAP DEVICES
swapoff /dev/block/zram1;
swapoff /dev/block/zram2;
swapoff /dev/block/zram3;
swapoff /dev/block/zram0;

echo 1 > /sys/block/zram1/reset;
echo 33554432 > /sys/block/zram1/disksize;
mkswap /dev/block/zram1;

echo 1 > /sys/block/zram2/reset;
echo 33554432 > /sys/block/zram2/disksize;
mkswap /dev/block/zram2;

echo 1 > /sys/block/zram3/reset;
echo 33554432 > /sys/block/zram3/disksize;
mkswap /dev/block/zram3;

echo 1 > /sys/block/zram0/reset;
echo 33554432 > /sys/block/zram0/disksize;
mkswap /dev/block/zram0;

busybox swapon -p 100 /dev/block/zram0;
busybox swapon -p 100 /dev/block/zram3;
busybox swapon -p 100 /dev/block/zram2;
busybox swapon -p 100 /dev/block/zram1;

echo 70 > /proc/sys/vm/swappiness;
exit
