#!/system/bin/sh

BBOX="/system/xbin/busybox"
NUMCPUS=`grep -c ^processor /proc/cpuinfo`
### ASSUME DUAL CORE IF WE GET ANY ERRORS
[ "$NUMCPUS" != 0 ] || NUMCPUS=2
### DECREMENTED NUMCUPS
DECR_NUMCPUS=$(($NUMCPUS - 1))
### CALCULATE ZRAMSIZE
RAMSIZE=$(grep MemTotal /proc/meminfo | grep -E --only-matching '[[:digit:]]+')
ZRAMSIZE=$(($RAMSIZE * 1024 / 2))

### INSMOD ZRAM-MODULE ON BOOT
if $BBOX [ -f /system/lib/modules/zram.ko ]; then
    if $BBOX [ -z "`$BBOX lsmod | $BBOX grep zram`" ]; then
        $BBOX insmod /system/lib/modules/zram.ko;
    fi;
    $BBOX modprobe zram zram_num_devices=$NUMCUPS;
fi; sleep 1


### CREATE ZRAM DEVICE(S)
for i in $(seq 0 $DECR_NUMCPUS); do
        if [ "$(grep /dev/block/zram$i /proc/swaps)" != "" ]; then
		$BBOX echo 1 > /sys/block/zram$i/reset;
sleep 1
fi; 	done;

for i in $(seq 0 $DECR_NUMCPUS); do
		$BBOX echo $ZRAMSIZE > /sys/block/zram$i/disksize;
	done;
for i in $(seq 0 $DECR_NUMCPUS); do
	if [ ! -f /sys/block/zram0/comp_algorithm ]; then
          	echo "Warning: cannot use LZ4 compression, defaulting to LZO (slower!)"
        else
         	$BBOX echo -n lz4 > /sys/block/zram0/comp_algorithm;
	fi; done;
for i in $(seq 0 $DECR_NUMCPUS); do
		$BBOX mkswap /dev/block/zram$i;
	done;
for i in $(seq 0 $DECR_NUMCPUS); do
		$BBOX swapon -p 100 /dev/block/zram$i;
        done; sleep 3
exit
